sudo: required
services:
  - docker

before_install:
  - docker build -t Teosoft7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Teosoft7/docker-react npm run test

language: generic
