sudo: required
services:
  - docker

before_install:
  - docker build -t teosoft7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true teosoft7/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-670212687244"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY

language: generic
